name: Windows RDP Free

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Enable RDP
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        net user runneradmin Password1234!

    - name: Install Node.js & LocalTunnel
      run: |
        npm install -g localtunnel

    - name: Start Tunnel & Get IP
      run: |
        # LocalTunnel ဖြင့် TCP 3389 ကို တိုက်ရိုက်ထုတ်ခြင်း
        Start-Process -FilePath "lt" -ArgumentList "--port 3389" -RedirectStandardOutput "lt.log" -WindowStyle Hidden
        Start-Sleep -Seconds 8

    - name: Show Connection Info
      run: |
        $url = Get-Content lt.log
        Write-Host "=========================================="
        Write-Host " YOUR RDP URL/ADDRESS: $url"
        Write-Host " Username: runneradmin"
        Write-Host " Password: Password1234!"
        Write-Host "=========================================="

    - name: Keep Alive (6 Hours)
      run: Start-Sleep -Seconds 21600
