name: Windows RDP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Enable RDP
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        net user runneradmin Password1234!

    - name: Start Tunnel & Get IP
      run: |
        ssh -o StrictHostKeyChecking=no -p 443 -R0:localhost:3389 a.pinggy.io > pinggy.log 2>&1 &
        Start-Sleep -Seconds 8
        Get-Content pinggy.log
        Write-Host "=========================================="
        Write-Host "Username: runneradmin"
        Write-Host "Password: Password1234!"
        Write-Host "=========================================="

    - name: Keep Alive (6 Hours)
      run: Start-Sleep -Seconds 21600
